from django.db import models


class AdsMdmTutor(models.Model):
    ds = models.CharField(max_length=8, help_text='数据日期 数据时间,yyyymmdd', primary_key=True)
    tutor_user_id = models.BigIntegerField(null=True, blank=True, help_text='教师标识')
    user_name = models.CharField(max_length=100, help_text='登录用户名')
    phone = models.CharField(max_length=30, help_text='电话')
    email = models.CharField(max_length=100, help_text='邮箱')
    avatar = models.CharField(max_length=256, help_text='用户头像')
    real_name = models.CharField(max_length=128, help_text='用户名称')
    gender_id = models.IntegerField(help_text='性别编号')
    gender_desc = models.CharField(max_length=10, help_text='性别描述')
    age = models.IntegerField(help_text='年龄')
    birthday = models.DateTimeField(help_text='生日')
    nationality_code = models.CharField(max_length=30, help_text='国籍编码')
    nationality_desc = models.CharField(max_length=30, help_text='国籍描述')
    residence_country_code = models.CharField(max_length=30, help_text='居住国家编码')
    residence_country_desc = models.CharField(max_length=30, help_text='居住国家描述')
    currency_code = models.CharField(max_length=30, help_text='货币编码')
    currency_desc_cn = models.CharField(max_length=30, help_text='货币中文描述')
    prefer_language_code = models.CharField(max_length=30, help_text='偏好语言编码')
    prefer_language_name = models.CharField(max_length=30, help_text='偏好语言名称')
    description_en = models.CharField(max_length=2047, help_text='英文描述')
    description_zh = models.CharField(max_length=2047, help_text='中文描述')
    rating_le = models.DecimalField(max_digits=10, decimal_places=2, help_text='学习环境')
    rating_id = models.DecimalField(max_digits=10, decimal_places=2, help_text='授课方法')
    rating_pk = models.DecimalField(max_digits=10, decimal_places=2, help_text='专业知识')
    rating_ot = models.DecimalField(max_digits=10, decimal_places=2, help_text='专业知识')
    rating_ot = models.DecimalField(max_digits=10, decimal_places=2)
    rating = models.DecimalField(max_digits=10, decimal_places=2, help_text='综合评分')
    teaching_start_time = models.DateTimeField(help_text='最早从事教学时间')
    lesson_num = models.IntegerField(help_text='总共上过几节课')
    balance_amt = models.DecimalField(max_digits=18, decimal_places=6, help_text='账户课时余额')
    is_hide = models.IntegerField(help_text='是否对学生隐藏')
    working_status_id = models.IntegerField(help_text='教师上岗状态')
    local_area_id = models.IntegerField(help_text='老师所属地区')
    is_full_work = models.IntegerField(help_text='是否全职')
    highest_degree_id = models.IntegerField(help_text='最高学历编号')
    highest_degree_desc = models.CharField(max_length=50, help_text='最高学历描述')
    is_school = models.IntegerField(help_text='是否在读')
    training_school = models.CharField(max_length=128, help_text='专科毕业学校')
    training_major = models.CharField(max_length=128, help_text='专科专业')
    bachelor_school = models.CharField(max_length=128, help_text='本科毕业学校')
    bachelor_major = models.CharField(max_length=128, help_text='本科专业')
    master_school = models.CharField(max_length=128, help_text='硕士毕业学校')
    master_major = models.CharField(max_length=128, help_text='硕士专业')
    doctor_school = models.CharField(max_length=128, help_text='博士毕业学校')
    doctor_major = models.CharField(max_length=128, help_text='博士专业')
    work_start_time = models.DateTimeField(help_text='开始工作时间')
    current_employer = models.CharField(max_length=128, help_text='目前就职单位')
    teacher_certificate = models.CharField(max_length=1023, help_text='教师资格证持证情况')
    teaching_style = models.CharField(max_length=256, help_text='教学风格')
    teaching_grade = models.CharField(max_length=128, help_text='擅长教授年级')
    chinese_level = models.CharField(max_length=32, help_text='普通话证书等级')
    english_level = models.CharField(max_length=32, help_text='英语证书等级')
    english_listening_speaking_ability = models.CharField(max_length=256, help_text='英语听说能力')
    other_foreign_language = models.CharField(max_length=256, help_text='其他外语')
    dialect = models.CharField(max_length=128, help_text='方言')
    remark = models.CharField(max_length=100, help_text='备注')
    identity_number = models.CharField(max_length=50, help_text='身份证号码')
    identity_name = models.CharField(max_length=100, help_text='身份证姓名')
    bank_account_number = models.CharField(max_length=50, help_text='银行账号')
    bank_name = models.CharField(max_length=100, help_text='银行名称')
    bank_branch_name = models.CharField(max_length=200, help_text='银行支行名称')
    last_login_tz = models.CharField(max_length=100, help_text='上次登录时区')
    login_tz = models.CharField(max_length=100, help_text='最近登录时区')
    last_login_time = models.DateTimeField(help_text='上次登录时间')
    login_time = models.DateTimeField(help_text='最新登录时间')
    user_status_id = models.IntegerField(help_text='用户状态')
    is_staff = models.IntegerField(help_text='是否公司员工')
    working_time = models.DateTimeField(help_text='上岗时间')
    tm_user_id = models.IntegerField(help_text='教师管理用户标识')
    create_time = models.DateTimeField(help_text='创建时间')
    trail_finish_class_student_num = models.IntegerField(help_text='累计完课学生数')
    trail_pay_student_num = models.IntegerField(help_text='累计付费学生数(付费 + 上课 > 1')
    trail_finish_class_student_num_30d = models.IntegerField(help_text='近30天完课学生数')
    trail_finish_class_student_num_60d = models.IntegerField(help_text='近60天完课学生数')
    trail_finish_class_student_num_90d = models.IntegerField(help_text='近90天完课学生数')
    trail_finish_class_student_num_180d = models.IntegerField(help_text='近180天完课学生数')
    formal_finish_class_num = models.IntegerField(help_text='累计完成课次')
    formal_finish_class_num_30d = models.IntegerField(help_text='近30天课次')
    formal_finish_class_num_60d = models.IntegerField(help_text='近60天课次')
    formal_inish_class_num_90d = models.IntegerField(help_text='近90天课次')
    formal_finish_class_num_180d = models.IntegerField(help_text='近180天课次')
    pair_finish_class_student_num = models.IntegerField(help_text='累计完课学生数')
    pair_finish_class_student_num_30d = models.IntegerField(help_text='近30天完课学生数')
    pair_finish_class_student_num_60d = models.IntegerField(help_text='近60天完课学生数')
    pair_finish_class_student_num_90d = models.IntegerField(help_text='近90天完课学生数')
    pair_finish_class_student_num_180d = models.IntegerField(help_text='近180天完课学生数')
    data_time = models.DateTimeField(null=True, blank=True)

    class Meta:
        db_table = 'ads_mdm_tutor'
